<template>
  <svg
    width="64"
    height="64"
    viewBox="0 0 64 64"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      cx="32"
      cy="32"
      r="30"

      fill="currentColor"
    />
    <ellipse
      cx="32"
      cy="32"
      rx="13.6533"
      ry="13.6533"
      fill="currentColor"
    />
    <rect
      x="44"
      y="30"
      width="17"
      height="4"
      fill="currentColor"
    />
    <rect
      x="2"
      y="30"
      width="17"
      height="4"
      fill="currentColor"
    />
    <circle
      cx="32"
      cy="32"
      r="8.96"
      fill="currentColor"
    />
  </svg>
</template>
